export const GET_MOVIE_ABOUT_REQUEST = "GET_MOVIE_ABOUT_REQUEST";
export const GET_MOVIE_ABOUT_SUCCESS = "GET_MOVIE_ABOUT_SUCCESS";

export const GET_TV_ABOUT_REQUEST = "GET_TV_ABOUT_REQUEST";
export const GET_TV_ABOUT_SUCCESS = "GET_TV_ABOUT_SUCCESS";

export const GET_PERSON_ABOUT_REQUEST = "GET_PERSON_ABOUT_REQUEST";
export const GET_PERSON_ABOUT_SUCCESS = "GET_PERSON_ABOUT_SUCCESS";

export const POST_MOVIE_REQUEST = "POST_MOVIE_REQUEST";
export const POST_MOVIE_SUCCESS = "POST_MOVIE_SUCCESS";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";

export const GET_WATCHLIST_MOVIE_REQUEST = "GET_WATCHLIST_MOVIE_REQUEST";
export const GET_WATCHLIST_MOVIE_SUCCESS = "GET_WATCHLIST_MOVIE_SUCCESS";

export const POST_TV_REQUEST = "POST_TV_REQUEST";
export const POST_TV_SUCCESS = "POST_TV_SUCCESS";

export const DELETE_TV_REQUEST = "DELETE_TV_REQUEST";
export const DELETE_TV_SUCCESS = "DELETE_TV_SUCCESS";

export const GET_WATCHLIST_TV_REQUEST = "GET_WATCHLIST_TV_REQUEST";
export const GET_WATCHLIST_TV_SUCCESS = "GET_WATCHLIST_TV_SUCCESS";

