export const GET_POPULAR_MOVIES_REQUEST = "GET_POPULAR_MOVIES_REQUEST";
export const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";

export const GET_TOP_RATED_MOVIES_REQUEST = "GET_TOP_RATED_MOVIES_REQUEST";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";

export const GET_POPULAR_SHOWS_REQUEST = "GET_POPULAR_SHOWS_REQUEST";
export const GET_POPULAR_SHOWS_SECCESS = "GET_POPULAR_SHOWS_SECCESS";

export const GET_TOP_RATED_SHOWS_REQUEST = "GET_TOP_RATED_SHOWS_REQUEST";
export const GET_TOP_RATED_SHOWS_SUCCESS = "GET_TOP_RATED_SHOWS_SUCCESS";