export const GET_SEARCH_MOVIES_REQUEST = "GET_SEARCH_MOVIES_REQUEST";
export const GET_SEARCH_MOVIES_SUCCESS = "GET_SEARCH_MOVIES_SUCCESS";

export const GET_SEARCH_TVSHOWS_REQUEST = "GET_SEARCH_TVSHOWS_REQUEST";
export const GET_SEARCH_TVSHOWS_SUCCESS = "GET_SEARCH_TVSHOWS_SUCCESS";

export const GET_SEARCH_PEOPLE_REQUEST = "GET_SEARCH_PEOPLE_REQUEST";
export const GET_SEARCH_PEOPLE_SUCCESS = "GET_SEARCH_PEOPLE_SUCCESS";

export const GET_POPULAR_MOVIES_REQUEST = "GET_POPULAR_MOVIES_REQUEST";
export const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";

export const GET_NOW_PLAYING_MOVIES_REQUEST = "GET_NOW_PLAYING_MOVIES_REQUEST";
export const GET_NOW_PLAYING_MOVIES_SUCCESS = "GET_NOW_PLAYING_MOVIES_SUCCESS";

export const GET_UPCOMING_MOVIES_REQUEST = "GET_UPCOMING_MOVIES_REQUEST";
export const GET_UPCOMING_MOVIES_SUCCESS = "GET_UPCOMING_MOVIES_SUCCESS";

export const GET_TOP_RATED_MOVIES_REQUEST = "GET_TOP_RATED_MOVIES_REQUEST";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";

export const GET_POPULAR_SHOWS_REQUEST = "GET_POPULAR_SHOWS_REQUEST";
export const GET_POPULAR_SHOWS_SECCESS = "GET_POPULAR_SHOWS_SECCESS";

export const GET_AIRING_TODAY_REQUEST = "GET_AIRING_TODAY_REQUEST";
export const GET_AIRING_TODAY_SUCCESS = "GET_AIRING_TODAY_SUCCESS";

export const GET_ON_TV_REQUEST = "GET_ON_TV_REQUEST";
export const GET_ON_TV_SUCCESS = "GET_ON_TV_SUCCESS";

export const GET_TOP_RATED_SHOWS_REQUEST = "GET_TOP_RATED_SHOWS_REQUEST";
export const GET_TOP_RATED_SHOWS_SUCCESS = "GET_TOP_RATED_SHOWS_SUCCESS";

export const GET_POPULAR_PEOPLE_REQUEST = "GET_POPULAR_PEOPLE_REQUEST";
export const GET_POPULAR_PEOPLE_SUCCESS = "GET_POPULAR_PEOPLE_SUCCESS";

export const GET_WATCHLIST_MOVIE_REQUEST = "GET_WATCHLIST_MOVIE_REQUEST";
export const GET_WATCHLIST_MOVIE_SUCCESS = "GET_WATCHLIST_MOVIE_SUCCESS";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";

export const GET_WATCHLIST_TV_REQUEST = "GET_WATCHLIST_TV_REQUEST";
export const GET_WATCHLIST_TV_SUCCESS = "GET_WATCHLIST_TV_SUCCESS";

export const DELETE_TV_REQUEST = "DELETE_TV_REQUEST";
export const DELETE_TV_SUCCESS = "DELETE_TV_SUCCESS";




